from __future__ import annotations
import random
from datetime import datetime,timedelta,timezone
from typing import Any
CLASSES=["DDOS","BOTNET_C2","DNS_TUNNELING","ENCRYPTED_MALWARE","DATA_EXFILTRATION","BENIGN","UNKNOWN_ANOMALY"]
SCENARIOS={"benign":("Benign enterprise baseline","Routine browsing, DNS, software updates, and business SaaS traffic."),"syn_flood":("SYN flood","A concentrated burst of TCP SYN packets without requiring return-flow visibility."),"udp_amplification":("UDP amplification","High-volume UDP traffic toward a concentrated target set."),"botnet":("Botnet beaconing","Highly regular small encrypted connections to a rare external destination."),"dns_tunnel":("DNS tunneling","Long, high-entropy subdomains with elevated query frequency."),"encrypted_malware":("Encrypted malware","Rare TLS fingerprints, periodic bursts, and unusual session-size patterns."),"exfiltration":("Data exfiltration","Sustained outbound bytes to a rare external destination beyond host baseline."),"mixed":("Coordinated mixed attack","All detectors receive correlated attack telemetry in a controlled simulation.")}
def _iso(dt):return dt.isoformat().replace("+00:00","Z")
def make_flows(count=160):
    rng=random.Random(42017);base=datetime(2026,9,2,10,42,tzinfo=timezone.utc);flows=[]
    for i in range(count):
        threat=CLASSES[i%len(CLASSES)] if i<112 else "BENIGN";protocol="DNS" if threat=="DNS_TUNNELING" else "UDP" if threat=="DDOS" and i%2 else "TCP"
        ranges={"BENIGN":(3,28),"UNKNOWN_ANOMALY":(45,69),"DDOS":(78,98),"BOTNET_C2":(67,91),"DNS_TUNNELING":(72,95),"ENCRYPTED_MALWARE":(70,96),"DATA_EXFILTRATION":(76,98)};risk=rng.randint(*ranges[threat]);packets=rng.randint(6,170);byte_count=packets*rng.randint(180,1380)
        if threat=="DDOS":packets,byte_count=rng.randint(9000,52000),rng.randint(12000000,86000000)
        if threat=="DATA_EXFILTRATION":byte_count=rng.randint(24000000,120000000)
        flows.append({"flow_id":f"FLOW-{0x8A7D21+i:06X}","timestamp":_iso(base-timedelta(seconds=i*19)),"sensor_id":f"DIODE-SENSOR-0{1+i%3}","src_ip":f"10.10.{1+i%8}.{20+i%210}","dst_ip":f"203.0.113.{10+(i*7)%220}","src_port":40000+(i*139)%24000,"dst_port":53 if protocol=="DNS" else 443 if i%4 else 8443,"protocol":protocol,"packet_length":min(1500,max(64,byte_count//max(packets,1))),"tcp_flags":["SYN"] if threat=="DDOS" else ["ACK","PSH"] if protocol=="TCP" else [],"direction":"observed_outbound" if i%4 else "observed_inbound","packets":packets,"bytes":byte_count,"duration_ms":rng.randint(40,180000),"risk":risk,"classification":threat,"severity":"critical" if risk>=90 else "high" if risk>=75 else "medium" if risk>=45 else "low","dns":{"query":f"{'a9f3'*12}.sync.example.net","query_length":64,"entropy":4.62} if threat=="DNS_TUNNELING" else None,"tls":{"sni":"updates.example.net","ja4":"t13d1516h2_8daaf6152771"} if protocol=="TCP" else None})
    return flows
def _evidence(threat,flow):
    data={"DDOS":[("packets_per_second",18420,910,.39,"Packet rate is 20.2× the sensor baseline."),("syn_flag_ratio",.94,.12,.31,"94% of observed TCP packets carried SYN flags."),("destination_concentration",.91,.18,.20,"Traffic converged on a small destination set.")],"BOTNET_C2":[("beacon_interval_cv",.028,.44,.41,"Traffic returned to the same destination at a highly regular 60-second interval."),("destination_rarity",.96,.21,.28,"The external destination is rare for this host."),("small_flow_repetition",47,4,.18,"Small, similarly sized flows repeated across the window.")],"DNS_TUNNELING":[("dns_query_entropy",4.62,2.31,.38,"The DNS query contained an unusually long, high-entropy subdomain."),("subdomain_length",64,13,.32,"Subdomain length exceeded the learned enterprise baseline."),("unique_query_ratio",.94,.28,.19,"Nearly all subdomain labels were unique.")],"ENCRYPTED_MALWARE":[("ja4_rarity",.98,.19,.34,"The observed JA4 fingerprint is rare in the sensor baseline."),("burst_periodicity",.91,.22,.29,"Encrypted flow bursts occurred with abnormal regularity."),("session_size_zscore",4.7,0,.21,"Session sizes deviated materially from peer behavior.")],"DATA_EXFILTRATION":[("outbound_baseline_ratio",8.9,1,.37,"Outbound traffic volume was 8.9 times higher than the established host baseline."),("destination_rarity",.96,.21,.28,"The external destination is rarely observed for this source."),("sustained_bytes",flow["bytes"],4200000,.22,"Sustained outbound volume persisted across consecutive windows.")],"UNKNOWN_ANOMALY":[("isolation_score",.78,.35,.43,"The flow is statistically isolated from recent peer behavior."),("protocol_shift",2.7,1,.23,"Protocol mix changed sharply within the active window.")]}
    return [{"feature":f,"value":v,"baseline":b,"contribution":c,"explanation":e} for f,v,b,c,e in data.get(threat,[])]
def make_alerts(flows,count=42):
    alerts=[]
    for i,flow in enumerate([f for f in flows if f["classification"]!="BENIGN"][:count]):
        threat=flow["classification"];alerts.append({"alert_id":f"ALT-2026-{421+i:05d}","timestamp":flow["timestamp"],"flow_id":flow["flow_id"],"sensor_id":flow["sensor_id"],"threat_class":threat,"severity":flow["severity"].upper(),"confidence":round(min(.99,.62+flow["risk"]/260),2),"source":{"ip":flow["src_ip"],"port":flow["src_port"]},"destination":{"ip":flow["dst_ip"],"port":flow["dst_port"]},"first_seen":flow["timestamp"],"last_seen":flow["timestamp"],"packet_count":flow["packets"],"byte_count":flow["bytes"],"protocol":flow["protocol"],"status":["new","investigating","contained"][i%3],"evidence":_evidence(threat,flow),"model":{"name":"Demo Metadata Ensemble","version":"1.2.0","mode":"demo","feature_schema":"oneway-v3"},"recommended_action":"Investigate the originating host and validate the destination through an independent administrative channel.","notes":[{"author":"Maya Chen","timestamp":flow["timestamp"],"text":"Queued for independent asset-owner validation."}] if i%4==0 else []})
    return alerts
def analytics():
    labels=["03:00","06:00","09:00","12:00","15:00","18:00","21:00","00:00"]
    return {"trend":[{"label":l,"alerts":8+(i*7)%19,"baseline":7+i%4} for i,l in enumerate(labels)],"traffic":[{"label":l,"mbps":42+(i*23)%78,"baseline":46+(i%3)*4} for i,l in enumerate(labels)],"categories":[{"name":c,"value":v} for c,v in zip(CLASSES[:-2],[31,18,17,14,20])],"protocols":[{"name":n,"value":v} for n,v in [("TCP",58),("UDP",23),("DNS",12),("QUIC",5),("ICMP",2)]],"confidence":[{"range":r,"count":v} for r,v in [("50–60",3),("60–70",7),("70–80",12),("80–90",18),("90–100",24)]],"latency":[{"label":l,"p50":18+i,"p95":38+i*2} for i,l in enumerate(labels)]}
